title: Tianxi Chen's Homepage
page-top-title: Tianxi Chen
top-section-bg-text: Computer Science
home-subtitle: Tianxi Chen&ensp;|&ensp;李森
copyright-text: '&copy; Tianxi Chen 2025. All Rights Reserved.'
